### ISSUE TITLE
Comparación entre Alternativas.

### ISSUE THREAD

**Issue by MirianSaucedo** [MirianSaucedo/TFGRealidadAumentada#6]
Esta tarea se procede a realizar una vez terminada la etapa de investigación y pruebas de las posibles herramientas.
Se observa y se debate las ventajas y desventajas que brinda cada uno de los mismos.

ESTA TAREA ES ASIGNADA A LA INTEGRANTE: Lizza López pero también será realizada por las demás integrantes: Mirian Saucedo y Pedro González. Ya que es una tarea que requiere opiniones entre los tres.

**Comment by lizzalorena** [comment]
Se realizo las comparaciones requeridas para elegir las herramientas definitivas a utilizar en el trabajo final de grado: Se estudio la posibilidad de utilizar Layar, Hoppala, entre otros navegadores de RA, finalmente se utiliza Metaio, con su SDK y su Arel. También se definió varias herramientas que se utilizaran.
