### ISSUE TITLE
Formación: Motor de BD, Gestor de Tareas y Versiones

### ISSUE THREAD

**Issue by MirianSaucedo** [MirianSaucedo/TFGRealidadAumentada#9]
Esta tarea comprende ampliar y afianzar los conocimientos acerca del motor de base de datos seleccionado para la realización del proyecto, así también del gestor de tareas y versiones.

La tarea debe ser realizada por los tres integrantes.

**Comment by lizzalorena** [comment]
La DB utilizada es MySQL, como gestor de tareas y versiones se esta utilizando el GitHub y el Kanbanflow
